apiVersion: v1
kind: Pod
metadata:
  name: fortune
spec:
  volumes:
  - name: data
    emptyDir: {}
  - name: web
    emptyDir: {}
  containers:
  - name: webserver
    image: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
    - name: web
      mountPath: /usr/share/nginx/html
      readOnly: true
  - name: teller
    image: alpine
    command:
      - sh
      - -c
      - |
        apk update && apk add bash fortune
        while true; do
          CONTENT=$(fortune)
          echo "<blockquote>$CONTENT</blockquote>" > /web/index.html
          echo "`date` - $CONTENT" >> /data/data.txt
          sleep 5
        done
    volumeMounts:
    - name: data
      mountPath: /data
      readOnly: false
    - name: web
      mountPath: /web
      readOnly: false
  - name: logger
    image: alpine
    command:
      - sh
      - -c
      - |
        while true; do
          if [ -f /var/fortune/data.txt ]; then
            tail -f /var/fortune/data.txt
          fi
          sleep 1
        done
    volumeMounts:
    - name: data
      mountPath: /var/fortune
      readOnly: true
