apiVersion: v1
kind: Pod
metadata:
  name: nginx-v1
spec:
  containers:
  - name: main
    image: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    env:
      - name: APP_VER
        value: "1.0"
    lifecycle:
      postStart:
        exec:
          command:
          - sh
          - -cx
          - |
            echo "{\"host\":\"$HOSTNAME\", \"ver\":\"$APP_VER\"}" > /usr/share/nginx/html/index.html