apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-v2
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: backend
      team: the-a-team
  template:
    metadata:
      labels:
        tier: backend
        team: the-a-team
    spec:
      containers:
      - name: main
        image: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 25m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 32Mi
        lifecycle:
          postStart:
            exec:
              command:
              - sh
              - -cx
              - |
                echo "{\"host\":\"$HOSTNAME\", \"ver\":\"$APP_VER\"}" > /usr/share/nginx/html/index.html
        env:
        - name: APP_VER
          value: "2.0"
