apiVersion: v1
kind: Pod
metadata:
  name: web-v1
  labels:
    tier: web
spec:
  containers:
  - name: main
    image: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      limits:
        cpu: 50m
        memory: 32Mi
      requests:
        cpu: 25m
        memory: 16Mi
    env:
      - name: APP_VER
        value: "1.0"
    lifecycle:
      postStart:
        exec:
          command:
          - sh
          - -cx
          - |
            echo "{\"host\":\"$HOSTNAME\", \"ver\":\"$APP_VER\"}" > /usr/share/nginx/html/index.html