apiVersion: v1
kind: Pod
metadata:
  name: web-v1
spec:
  containers:
  - name: main
    image: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    lifecycle:
      postStart:
        exec:
          command:
          - sh
          - -cx
          - |
            echo "{\"host\":\"$HOSTNAME\", \"ver\":\"$APP_VER\"}" > /usr/share/nginx/html/index.html
    env:
    - name: APP_VER
      value: "1.0"
