---
apiVersion: v1
kind: ConfigMap
metadata:
  name: boot-config
data:
  SPRING_PROFILES_ACTIVE: externaldb
  SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/testdb
---
apiVersion: v1
kind: Service
metadata:
  name: boot
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    tier: boot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: boot
  template:
    metadata:
      labels:
        tier: boot
    spec:
      containers:
      - name: main
        image: maliksalman/dockerdemo:native-1.0
        envFrom:
        - configMapRef:
            name: boot-config
        ports:
        - containerPort: 8080
          protocol: TCP
