---
apiVersion: v1
kind: ConfigMap
metadata:
  name: boot-config
data:
  SPRING_PROFILES_ACTIVE: localpg
  SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
---
apiVersion: v1
kind: Service
metadata:
  name: boot
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    tier: boot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot
spec:
  replicas: 3
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      tier: boot
  template:
    metadata:
      labels:
        tier: boot
    spec:
      containers:
      - name: app
        image: maliksalman/spring-data-jdbc-sample:native-1.0
        envFrom:
        - configMapRef:
            name: boot-config
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /heroes
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
