apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    tier: db
spec:
  containers:
  - name: main
    image: postgres:15
    env:
    - name: POSTGRES_PASSWORD
      value: secret
    ports:
    - containerPort: 5432
    resources:
      limits:
        cpu: 256m
        memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    tier: db
