apiVersion: apps/v1
kind: Deployment
metadata:
  name: configdemo
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: main
          image: nginx
          env:
            - name: MY_VAR
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: HELLO
          ports:
            - containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -cx
                  - |
                    echo "{\"host\":\"$HOSTNAME\", \"hello\":\"$MY_VAR\"}" > /usr/share/nginx/html/index.html
