apiVersion: apps/v1
kind: Deployment
metadata:
  name: cfg-app
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      tier: cfg
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        tier: cfg
    spec:
      volumes:
        - name: secret-vol
          secret:
            secretName: my-secret
      containers:
        - name: main
          image: nginx
          volumeMounts:
            - name: secret-vol
              mountPath: /etc/secrets
              readOnly: true
          ports:
            - containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -cx
                  - |
                    QUOTE=$(head -1 /etc/secrets/QUOTE)
                    echo "{\"host\":\"$HOSTNAME\", \"quote\":\"$QUOTE\"}" > /usr/share/nginx/html/index.html
