apiVersion: apps/v1
kind: Deployment
metadata:
  name: configdemo
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      volumes:
        - name: config-vol
          configMap:
            name: my-config
      containers:
        - name: main
          image: nginx
          volumeMounts:
            - name: config-vol
              mountPath: /etc/config
              readOnly: true
          ports:
            - containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -cx
                  - |
                    FIRST_NAME=$(head -1 /etc/config/INFO)
                    echo "{\"host\":\"$HOSTNAME\", \"name\":\"$FIRST_NAME\"}" > /usr/share/nginx/html/index.html
